### ISSUE TITLE
Deployment issue. 

### ISSUE THREAD

**Issue by afidegnum** [arctic-hen7/perseus#81]
**Describe the bug**
Even though i was able to run `perseus serve` correctly, 
after deployment via `perseus deploy ` I tried running `./server`, i'm then greeted with the following error: 

```
./server 
thread 'actix-rt:worker:0' panicked at 'Couldn't get render configuration!: StoreError(NotFound { name: "./dist/render_conf.json" })', /home/afidegnum/.cargo/registry/src/github.com-1ecc6299db9ec823/perseus-actix-web-0.3.0-beta.17/src/configurer.rs:75:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'actix-rt:worker:1' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/afidegnum/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:2' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/afidegnum/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:3' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/afidegnum/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:4' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/afidegnum/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:5' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/afidegnum/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:6' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/afidegnum/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36
thread 'actix-rt:worker:7' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /home/afidegnum/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:282:36

```

and I had a `ERR_SOCKET_NOT_CONNECTED`  error while trying to launch from the browser
**To Reproduce**
perseus deploy inside the root

Here is the following repo. https://github.com/afidegnum/fronttest

**Comment by afidegnum** [comment]
ok, i got it 
I had to export PERSEUS_STANDALONE=true
